version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./public:/app/public
      - ./server:/app/server
      - ./store:/app/store
      - ./styles:/app/styles
      - ./helpers:/app/helpers
      - ./modules:/app/modules
      - ./ui:/app/ui
      - /app/node_modules
    ports:
      - 5001:5001
