import React, { FC } from 'react';
import NextHead from 'next/head';

const Head: FC = () => {
  return (
    <NextHead>
      <title>Next App</title>
      <meta name='description' content='Generated by create next app' />
    </NextHead>
  );
};

export default Head;
